#!/usr/bin/env bash
# script to install nginx web server

sudo apt-get update
sudo apt-get install -y nginx

sudo service nginx start
sudo bash -c 'echo "server {
	listen 80;
	server_name _;
	
	location / {
		echo \"Hello World!\";
	}
}" > /etc/nginx/sites-available/default'

sudo service nginx reload
sudo service nginx status
