#!/usr/bin/env bash
# script to run nginx as nginx and not superuser

if ! command -v nginx &>/dev/null;
then
	apt-get update
	apt-get install -y nginx
fi

service nginx stop
chmod 777 /etc/nginx/nginx.conf

sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

su nginx -c "service nginx start"
