#!/usr/bin/env bash
# script to run nginx as nginx and not superuser
service nginx stop
chmod 777 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80/8080;/g' /etc/nginx/sites-available/default
su nginx -c "service nginx start"
